### ISSUE TITLE
Proposal: in-place print() replacement 

### ISSUE THREAD

**Issue by nickdelgrosso** [abcnishant007/smartprint#7]
Hi,

If you handle keyword arguments, smartprint() could work as an in-place print() replacement just by altering the import line:

```python
from smartprint import smartprint as print
```

This would be great in cases where print is only being used for debugging

**Comment by abcnishant007** [comment]
@nickdelgrosso  
Can you resend this pull request? 
I added some tests, hence old pull requests are causing conflicts.

**Comment by abcnishant007** [comment]
Ignore the previous comment, I resolved the conflicts manually,

I will add this in the readMe,
just this change makes the whole thing super usable with existing code!
